"""empty message

Revision ID: 2fdc5d7e70a7
Revises: 0709e920b4ac
Create Date: 2020-05-21 09:16:48.099022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdc5d7e70a7'
down_revision = '0709e920b4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=150), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('created_on', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
