"""empty message

Revision ID: ba60874e77e6
Revises: 36d31c92461a
Create Date: 2020-05-18 22:35:12.523322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba60874e77e6'
down_revision = '36d31c92461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follows_user_id_key', 'follows', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('follows_user_id_key', 'follows', ['user_id'])
    # ### end Alembic commands ###
